ir_info_config = {
    'log_file':'IRSampleAnalysisInfo.log',
#     'sample_list':'sample_source_files/WTCHG_samples_info.csv',
    'sample_list':"sample_source_files/WTCHG_quasar_sample_info.csv",
    #'sample_list':'oracle_samplesTSBsteering.csv',
    'ir_sample_file':'IR_source_files/IonReporter_Sample_Data_14_01_2014.csv',
    'ir14_analysis_file':'IR_source_files/analysis_summary_14.csv',
    'ir16_analysis_file':'IR_source_files/analysis_summary_16.csv',
    'output_file':'ir_info.csv'
}

# the samples here dont have a match in the script input files
# "archived" ones dont have a pdf uploaded in TS, but are still present in results/analysis/output/Home/
# "missing" ones do have a full pdf in TS, but are saved in results/OX1 or OX2 

manual_match = {"QUASAR2_C01":"Archived",
"QUASAR2_E01":"Archived",
"QUASAR2_F01":"Archived",
"QUASAR2_G01":"Archived",
"QUASAR2_H01":"Archived",
"QUASAR2pl1_A06":"Archived",
"QUASAR2pl1_A08N":"Archived",
"QUASAR2pl1_A09T":"Archived",
"QUASAR2pl1_B06":"Archived",
"QUASAR2pl1_B08N":"Archived",
"QUASAR2pl1_B09":"Archived",
"QUASAR2pl1-C03":"Archived",
"QUASAR2pl1_C08T":"Archived",
"QUASAR2pl1_C09":"Archived",
"QUASAR2pl1_D03":"Archived",
"QUASAR2pl1_D08T":"Archived",
# "QUASAR2pl1_D09":"Archived",
"QUASAR2pl1-E03":"Archived",
"QUASAR2pl1_E08N":"Archived",
"QUASAR2pl1_E09":"Archived",
"QUASAR2pl1_E11":"Archived",
"QUASAR2pl1_F08N":"Archived",
"QUASAR2pl1-G04":"Archived",
"QUASAR2pl1_G07T":"Archived",
"QUASAR2pl1_G08T":"Archived",
"QUASAR2pl1-H04":"Archived",
"QUASAR2pl1_H05":"Archived",
"QUASAR2pl1_H07T":"Archived",
"QUASAR2pl1_H08T":"Archived",
"VICTORindels-B03(9B)":"Missing",
"Mesothelioma_01":"Archived",
"Mesothelioma_02":"Archived",
"Mesothelioma_03rpt":"Archived",
"Mesothelioma_04":"Archived",
"Mesothelioma_05":"Archived",
"Mesothelioma_06":"Archived",
"Mesothelioma_07rpt":"Archived",
"Mesothelioma_08":"Archived",
"Mesothelioma_09":"Archived",
"Mesothelioma_10":"Archived",
"CRC-FAP3":"Archived",
"CRC-PH3":"Archived",
"CRC-PH5":"Archived",
"ENDO_03rpt":"Archived",
"ENDO_12":"Archived",
"ENDO_15":"Archived",
"S.Am-01":"Missing",
"S.Am-04":"Missing",
"S.Am-06":"Missing",
"S.Am-IBG2":"Missing",
"S.Am-IBG2":"Missing"

}